//@version=5
indicator(title="Multiple Moving Average & Golden, Death Crossinngs", shorttitle="mmA&gdc", overlay=true, timeframe="", timeframe_gaps=true)

len7 = input.int(7, minval=1, title="Length")
len20 = input.int(20, minval=1, title="Length")
len50 = input.int(50, minval=1, title="Length")
len100 = input.int(100, minval=1, title="Length")
len200 = input.int(200, minval=1, title="Length")

//EMA
emalen5 = input.int(5, minval=1, title="Length")
emalen13 = input.int(13, minval=1, title="Length")
emalen21 = input.int(21, minval=1, title="Length")
emalen34 = input.int(34, minval=1, title="Length")
emalen55 = input.int(55, minval=1, title="Length")
emalen89 = input.int(89, minval=1, title="Length")
emalen144 = input.int(144, minval=1, title="Length")
//EMA

src = input(close, title="Source")
offset = input.int(title="Offset", defval=0, minval=-500, maxval=500)

closedPrice = src

out7 = ta.sma(src, len7)
out20 = ta.sma(src, len20)
out50 = ta.sma(src, len50)
out100 = ta.sma(src, len100)
out200 = ta.sma(src, len200)

//OUT emaS
outEma5 = ta.ema(src, emalen5)
outEma13 = ta.ema(src, emalen13)
outEma21 = ta.ema(src, emalen21)
outEma34 = ta.ema(src, emalen34)
outEma55 = ta.ema(src, emalen55)
outEma89 = ta.ema(src, emalen89)
outEma144 = ta.ema(src, emalen144)

plot(outEma5, color=color.white, title="EMA 5", offset=offset, display=display.none)
plot(outEma13, color=color.teal, title="EMA 13", offset=offset, display=display.none)
plot(outEma21, color=color.blue, title="EMA 21", offset=offset, display=display.none)
plot(outEma34, color=color.orange, title="EMA 34", offset=offset, display=display.none)
plot(outEma55, color=color.yellow, title="EMA 55", offset=offset, display=display.none)
plot(outEma89, color=color.red, title="EMA 89", offset=offset, display=display.none)
plot(outEma144, color=color.purple, title="EMA 144", offset=offset, display=display.none)
//Out emaS

plot(out7, color=color.white, title="MA 7", offset=offset, display=display.none)
plot(out20, color=color.blue, title="MA 20", offset=offset, display=display.none)
plot(out50, color=color.yellow, title="MA 50", offset=offset, display=display.none)
plot(out100, color=color.red, title="MA 100", offset=offset, display=display.none)
plot(out200, color=color.purple, title="MA 200", offset=offset, display=display.none)

ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

typeMA = input.string(title = "Method", defval = "SMA", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="Smoothing")
smoothingLength = input.int(title = "Length", defval = 5, minval = 1, maxval = 100, group="Smoothing")

longCond = ta.crossover(out50, out200)
//shortCond = ta.crossover(out20, out7) and (out20 > out7)
shortCond = ta.crossunder(out50, out200)

//EMA Signals
buyCond = ta.crossover(outEma5, outEma13)
buyCondStrong = ta.crossover(outEma13, outEma21)

plotshape(series=buyCond, title="EMA 5,13 Buy Crossing", style=shape.labelup, location=location.belowbar, color=color.green, offset=0, text='▲', textcolor=color.white, size=size.auto, display=display.none)
plotshape(series=buyCondStrong, title="EMA 13,21 Buy Crossing", style=shape.labelup, location=location.belowbar, color=color.green, offset=0, text='▲▲', textcolor=color.white, size=size.auto, display=display.none)
plotshape(series=buyCondStrong, title="EMA 13,21 Buy Crossing After Ema 13 STOP", style=shape.labelup, location=location.belowbar, color=color.red, offset=0, text='STOP', textcolor=color.white, size=size.auto, display=display.none)
//Ema Signals

plotshape(series=longCond, title="Golden Cross", style=shape.labelup, location=location.belowbar, color=color.green, offset=0, text='▲', textcolor=color.white, size=size.auto, display=display.none)
plotshape(series=shortCond, title="Death Cross", style=shape.labelup, location=location.abovebar, color=color.red, offset=0, text='▼', textcolor=color.white, size=size.auto, display=display.none)

alertcondition(buyCondStrong, title="Strong Long", message="Strong Long")
//smoothingLine = ma(out, smoothingLength, typeMA)
//plot(smoothingLine, title="Smoothing Line", color=#f37f20, offset=offset, display=display.none)